FROM jupyter/scipy-notebook:python-3.10

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/jupyter-notebook-custom-image

ARG VERSION_LOWER=0.7.0
ARG VERSION_UPPER=0.8.0

RUN pip install jupyterlab-s3-browser && \
    jupyter serverextension enable --py jupyterlab_s3_browser && \
    python -m pip install "digitalhub[full]>=${VERSION_LOWER}, <${VERSION_UPPER}" \
                          "digitalhub-runtime-python>=${VERSION_LOWER}, <${VERSION_UPPER}" \
                          "digitalhub-runtime-container>=${VERSION_LOWER}, <${VERSION_UPPER}"  \
                          "digitalhub-runtime-modelserve>=${VERSION_LOWER}, <${VERSION_UPPER}" \
                          "digitalhub-runtime-dbt[local]>=${VERSION_LOWER}, <${VERSION_UPPER}" && \
    python -m pip install "digitalhub-runtime-kfp>=${VERSION_LOWER}, <${VERSION_UPPER}" --no-deps

