FROM jupyter/minimal-notebook:python-3.11

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/jupyter-notebook-custom-image

ARG ver_sdk=0.11.0
ARG ver_python=0.11.0
ARG ver_container=0.11.0
ARG ver_modelserve=0.11.0b3
ARG ver_dbt=0.11.0
ARG ver_kfp=0.11.0

RUN python -m pip install "digitalhub[full]==${ver_sdk}" \
                          "digitalhub-runtime-python==${ver_python}" \
                          "digitalhub-runtime-container==${ver_container}"  \
                          "digitalhub-runtime-modelserve==${ver_modelserve}" \
                          "digitalhub-runtime-dbt[local]==${ver_dbt}" \
                          "digitalhub-runtime-kfp==${ver_kfp}"
