FROM quay.io/mlrun/jupyter:1.4.0

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/jupyter-notebook-custom-image

# Create conda env for digitalhub-core kernel
RUN conda create -n digitalhub-core python=3.9 --no-default-packages

# Clone digitalhub-core repo
ARG DHUB_VERSION=0.0.9
RUN wget https://github.com/scc-digitalhub/digitalhub-sdk/archive/refs/tags/$DHUB_VERSION.zip
RUN unzip $DHUB_VERSION.zip
RUN mv digitalhub-sdk-$DHUB_VERSION digitalhub-sdk

# Install remote-only dependencies in base kernel
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]
RUN pip install digitalhub-sdk/core
RUN pip install digitalhub-sdk/data/modules/dbt
RUN pip install digitalhub-sdk/data/modules/nefertem

# Install full dependencies in digitalhub-core kernel
SHELL ["conda", "run", "-n", "digitalhub-core", "/bin/bash", "-c"]
RUN python -m pip install ipykernel
RUN python -m ipykernel install --name digitalhub-core --display-name "digitalhub-core" --user

# Install digitalhub-core, dbt, neferetem
RUN pip install digitalhub-sdk/core
RUN pip install digitalhub-sdk/data/modules/dbt[local]
RUN pip install digitalhub-sdk/data/modules/nefertem[local]

# Install nefertem plugins
RUN wget https://github.com/scc-digitalhub/nefertem/archive/refs/tags/v2.0.2.zip
RUN unzip v2.0.2.zip
RUN mv nefertem-2.0.2 nefertem
RUN pip3 install ./nefertem/plugins/frictionless*
RUN pip3 install ./nefertem/plugins/duckdb*
RUN pip3 install ./nefertem/plugins/sqlalchemy*
RUN pip3 install ./nefertem/plugins/ydata*

# Copy notebooks into tutorial folder
COPY notebooks/ /home/jovyan/tutorial

# Cleanup
RUN rm -rf digitalhub-sdk nefertem $DHUB_VERSION.zip
