# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0
FROM jupyter/minimal-notebook:python-3.9

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/jupyter-notebook-custom-image

ARG ver_sdk=0.14.7
ARG ver_python=0.14.2
ARG ver_container=0.14.2
ARG ver_modelserve=0.14.4
ARG ver_dbt=0.14.2
ARG ver_kfp=0.14.2
ARG ver_hera=0.14.1
ARG ver_flower=0.14.0

RUN python -m pip install "digitalhub[full]==${ver_sdk}" \
                          "digitalhub-runtime-python==${ver_python}" \
                          "digitalhub-runtime-container==${ver_container}"  \
                          "digitalhub-runtime-modelserve==${ver_modelserve}" \
                          "digitalhub-runtime-dbt[local]==${ver_dbt}" \
                          "digitalhub-runtime-kfp==${ver_kfp}" \
                          "digitalhub-runtime-flower==${ver_flower}" \
                          "digitalhub-runtime-hera==${ver_hera}"
